[tool.poetry]
name = "HypEx"
version = "0.0.3"
description = "Fast and customizable framework for Causal Inference"
authors = [
    "Dmitry Tikhomirov <dimasta00@gmail.com>",
]
readme = "README.md"
license = "Apache-2.0"
repository = "https://github.com/sb-ai-lab/HypEx"
classifiers = [
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Natural Language :: English",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Typing :: Typed",
]


[tool.poetry.dependencies]
python = ">=3.8, <3.11"
tqdm = "*"
scikit-learn = "*"

pandas = [
    { version = ">=1.3.5, <=2.0.3", python = "<3.9" },
    { version = ">=1.3.5, <=2.1.3", python = ">=3.9" }
]

numpy = [
    { version = ">=1.17.0, <=1.24.4", python = "<3.9" },
    { version = ">=1.17.0, <=1.26.2", python = ">=3.9" }
]

scipy = [
    { version = ">=1.5.0, <=1.10.1", python = "<3.9" },
    { version = ">=1.5.0, <=1.11.3", python = ">=3.9, <3.11" }
]

matplotlib = [
    { version = ">=3.0.0, <=3.7.3", python = "<3.9" },
    { version = ">=3.0.0, <=3.8.1", python = ">=3.9, <3.11" }]

faiss-cpu = ">=1.6.0, <=1.7.4"


[tool.poetry.dev-dependencies]
jupyter = "^1.0.0"
pytest = "^7.4.3"

sphinx = { version = "^7.2.6", python = ">=3.9, <3.11" }
nbsphinx = "*"
nbsphinx_link = "*"
sphinx_autodoc_typehints = "*"
sphinx_rtd_theme = "^1.2.2"




[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''


[tool.isort]
profile = "black"
force_single_line = true
atomic = true
include_trailing_comma = true
lines_after_imports = 2
lines_between_types = 1
use_parentheses = true
filter_files = true


[tool.mypy]
files = ["hypex", "tests"]
ignore_missing_imports = false
disallow_untyped_defs = true
disallow_untyped_calls = true
warn_redundant_casts = true
warn_return_any = true
check_untyped_defs = true


[tool.flake8]
max-line-length = 120
ignore = [
    "E203", # Whitespace before ":" (Black compatibility)
    "E266", # Too many leading "#" for block comment
    "E501", # Line too long (handled by Black)
    "W503", # Line break before binary operator (Black compatibility)
]
exclude = [
    ".venv",
    ".git",
    "__pycache__",
    "build",
    "dist"
]
