[tool.poetry]
name = "HypEx"
version = "0.0.1b1"
description = "Fast and customizable framework for Causal Inference"
authors = [
    "Dmitry Tikhomirov <dimasta00@gmail.com>",
    "Anton Gabov <@gmail.com>", # TODO
]
readme = "README.md"
license = "Apache-2.0"
homepage = "https://lightautoml.readthedocs.io/en/latest/" # TODO
repository = "https://github.com/sb-ai-lab/HypEx"
classifiers = [
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Natural Language :: English",
    "Topic :: Scientific/Engineering :: Artificial Intelligence:: Causal Inference",
    "Typing :: Typed"
]


[tool.poetry.dependencies]
python = ">=3.8, <3.11"
tqdm = '*'
scikit-learn = "*"

pandas = [
    { version = "^2.0.3", python = "<3.9" },
    { version = "*", python = ">=3.9" }
]

numpy = [
    { version = "^1.24.4", python = "<3.9" },
    { version = "*", python = ">=3.9" }
]

scipy = [
    { version = "^1.11.1", python = "<3.9" },
    { version = "*", python = ">=3.9" }
]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"